import '@/style/reset.css';
import '@/style/global.css';
import { fontPretendard } from '@/style/fontPretendard';
import { Metadata, Viewport } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        rel: 'icon',
        type: 'image/png',
        sizes: '64x64',
        url: '/image/favicon/favicon-64x64.png',
      },
    ],
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang='ko' className={fontPretendard.className}>
      {/* <html lang='ko'> */}
      <body>{children}</body>
    </html>
  );
}
